### ISSUE TITLE
fix Coc for DoD

### ISSUE THREAD

**Issue by mariapaulafn** [Department-of-Decentralization/decentralala.com#2]
Guys, it reads too much like copy-paste for ethberlin, needs to be less about code

**Comment by pstehlik** [comment]
Fair enough. 
I had worked the initial version with edits from Helena and then posting for feedback to the group.

I can take a stab at another round of edits at some point in the next couple of weeks but would want to make sure we capture the right spirit then. Any other feedback from anyone except too much code?

**Comment by mariapaulafn** [comment]
Nope, that's it - the rest is perf! thanks @pstehlik
